config:
  google_tag_manager_id:
    type: text
    required: false
    label: Your google tag manager id

  tarteaucitron_multipletagua
    type: text
    required: false
    label: Your google tag UA
